### ISSUE TITLE
Update Exchange top menu

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Frontend#216]
Items should be centered like Art menu.

<img width="1360" alt="Screen Shot 2024-04-22 at 8 52 38 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/d1b1448a-0103-47bb-b405-00c2ecb78e4c">

<img width="1361" alt="Screen Shot 2024-04-22 at 8 52 50 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/7c4bad33-9510-4213-b921-1ca7ac4f98c8">

**Comment by Der12kl** [comment]
use flex display: flex;
   justify-content: center;
   align-items: center;
