### ISSUE TITLE
ReferenceError mdiPlusCircle is not defined

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Frontend#221]
https://thenewboston.sentry.io/issues/5240815623/?project=4507120966959104&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0

**Comment by MAbdurrehman1** [comment]
@buckyroberts This seems be to on a local setup.
I think we can either remove or comment out the sentry DSN from our local setups

<img width="744" alt="image" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/52558124/53152a67-7952-4566-a383-578cccf95413">
