### ISSUE TITLE
Update University icon

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Frontend#236]
# Old

<img width="335" alt="Screen Shot 2024-04-23 at 9 56 36 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/5f733e3a-ca48-4200-bef1-5297f761111d">

# New

<img width="130" alt="Screen Shot 2024-04-26 at 8 12 54 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/4f9e4049-61a6-444d-b12f-609a0c90cd1a">

**Comment by DesunTech** [comment]
![Screenshot (45)](https://github.com/thenewboston-developers/thenewboston-Frontend/assets/96474971/6889d268-f6f7-4fe9-a539-6b64261e608a)



fixed in branch 236-Update-University-icon
