### ISSUE TITLE
White page bug

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Frontend#242]
<img width="801" alt="Screen Shot 2024-05-04 at 1 37 05 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/88839317-413d-494b-94dc-dd35c3803e84">

![Screenshot_20240504-133540](https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/54be274b-0d15-4e05-895a-a6d05e0c2d65)

**Comment by sagar-vaghela** [comment]
@buckyroberts 

Could you please tell me how can I reproduce this issue?

**Comment by buckyroberts** [comment]
Your Redux state has to be out of sync with your reducers. So just mess it up in some way, delete some random objects or something. It happens when we release because the reducer source code is updated but it’s out of sync with the data it loads in from local storage.
