### ISSUE TITLE
Lecture page design

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Frontend#244]
Update lecture page design. Do not include the Ia section, we will be building that feature later.

<img width="1497" alt="Screen Shot 2024-04-25 at 8 35 29 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/e9e2a362-ac9a-447d-8a8e-05e1686e84a1">

**Comment by sagar-vaghela** [comment]
@buckyroberts 

Updated design:
![image](https://github.com/thenewboston-developers/thenewboston-Frontend/assets/30215189/ade41ed2-e15d-40f7-b95d-a10dacf2d58d)

Currently, I implemented this new figma design but the data from BE is not matching with this UI. Then should I take dummy data or use existing one?

**Comment by buckyroberts** [comment]
@sagar-vaghela for any data we are missing from the backend we can just leave those design elements out.

**Comment by buckyroberts** [comment]
@sagar-vaghela what data is not matching?
