### ISSUE TITLE
Update global modal styling

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Frontend#245]
This includes heading, close icon, line, padding. **This task does not include any form elements or modal contents.**

<img width="871" alt="Screen Shot 2024-04-25 at 8 49 03 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/86a45c6d-e21f-4fe0-94b7-6cdfb8facd42">

**Comment by MAbdurrehman1** [comment]
@buckyroberts This is what the modal looks like ATM:

It doesn't have the rounded input fields but I'm assuming we are not making any form elements or modal contents changes.

<img width="575" alt="image" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/52558124/b2818af0-9301-49e2-96b1-e998df7dd40c">
