### ISSUE TITLE
Update button styles

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Frontend#246]
Update button styles based on new Figma designs and color scheme.

<img width="377" alt="Screen Shot 2024-04-25 at 8 50 48 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/8b179dff-12ef-449c-990e-f7e371700786">

**Comment by sagar-vaghela** [comment]
![image](https://github.com/thenewboston-developers/thenewboston-Frontend/assets/30215189/fbd4fd35-ec87-49ea-8995-6b9f35db2710)

Should I follow this updated button design across the board?

**Comment by buckyroberts** [comment]
Not the one you posted, that’s from an old design. Find the Figma element from the one I posted and use that as our new style in the Button component.
