### ISSUE TITLE
Standardize scrolling behavior

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Frontend#261]
When scrolling on the University pages, the header should be sticky (like the Art pages).

<img width="1397" alt="Screen Shot 2024-04-28 at 7 17 03 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/cde28e0e-3036-4940-a9c5-6defecf983e1">

<img width="1397" alt="Screen Shot 2024-04-28 at 7 17 13 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/e4b98289-39fc-4ea6-b614-2e07fcc4817e">

**Comment by MAbdurrehman1** [comment]
@buckyroberts So there are 2 scrolls on this page: 1 is the infinite scroll and 2 is the page scroll.
Header remains sticky on the infinite scroll but it moves on the page scroll.


https://github.com/thenewboston-developers/thenewboston-Frontend/assets/52558124/e081d1a4-d9b2-4ad2-8735-94f4d9b6ff85


Anyhow, the [PR](https://github.com/thenewboston-developers/thenewboston-Frontend/pull/279) attached with this has alot of irrelevant and widespread changes which I'm not confident to merge. So I'm going to close it, and open a another one,
