### ISSUE TITLE
Profile page header and avatar redesign

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Frontend#264]
<img width="1747" alt="Screen Shot 2024-05-04 at 1 17 53 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/bc03daad-461b-4c0e-a0d7-f5ec50baffe6">

**Comment by sagar-vaghela** [comment]
![image](https://github.com/thenewboston-developers/thenewboston-Frontend/assets/30215189/d1f57cc0-e8dd-4827-9dda-0844c9379ac1)

@buckyroberts 

Is this updated design?

**Comment by buckyroberts** [comment]
@sagar-vaghela just do the red background part and the avatar. Leave everything else the same.
