### ISSUE TITLE
Redirect to an appropriate page after deleting an artwork

### ISSUE THREAD

**Issue by MAbdurrehman1** [thenewboston-developers/thenewboston-Frontend#282]
Currently, if you delete an artwork from the artwork details page, you are left on that same page which is blank so this might confuse users:

<img width="1146" alt="image" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/52558124/4c83392d-2d18-46bd-8450-4789169be1f8">

<img width="519" alt="image" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/52558124/34b20373-c947-49ef-9e6a-ba15eee49c35">

<img width="1432" alt="image" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/52558124/2e628627-e325-4650-aa44-865dcc046658">

I think we should redirect the user to the artworks list page once they do this.

**Comment by buckyroberts** [comment]
When I deleted artwork from the same page, I will still stuck on that page but instead of seeing a blank page like above ^ my page showed the same data but an error saying "Error fetching details". As part of this ticket we also need to make sure our Redux state is being cleaned up properly.
