### ISSUE TITLE
Total Contributions by day

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Frontend#340]
This ticket is for the frontend part of this ticket: https://github.com/thenewboston-developers/thenewboston-Backend/issues/187

Once the backend is ready, fetch the data from that endpoint. We should no longer need to do any calculations on the frontend.

<img width="815" alt="Screen Shot 2024-05-12 at 5 25 05 PM" src="https://github.com/thenewboston-developers/thenewboston-Frontend/assets/8547538/566fd249-b5a2-4682-8677-155639061f8d">

**Comment by MAbdurrehman1** [comment]
@buckyroberts This was done in this PR https://github.com/thenewboston-developers/thenewboston-Frontend/pull/388, so closing this issue.
