### ISSUE TITLE
Need a vertical scroll bar for the `feeds` section

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/thenewboston-Frontend#395]
After scrolling for 5 minutes looking at the cool posts, I realized there was no way to go up without moving the mouse wheel for another 5 minutes.

![Untitled](https://github.com/thenewboston-developers/thenewboston-Frontend/assets/22790904/8fa85425-60dc-4561-b4aa-2e59b52af20d)

**Comment by MAbdurrehman1** [comment]
I suggest displaying an upward arrow icon when the user scrolls down. Clicking on this icon will automatically scroll the page back to the top.
