### ISSUE TITLE
Notification icon issue

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/thenewboston-Frontend#418]
On the Notification page, the icons do not appear in the correct place when scrolling. It also causes the left menu to shift up from the bottom when it should not.

<img width="359" alt="Screen Shot 2024-07-21 at 12 01 23 PM" src="https://github.com/user-attachments/assets/209f5c00-706d-49d4-bdd9-b9a14e0043d6">

<img width="1479" alt="Screen Shot 2024-07-21 at 12 03 03 PM" src="https://github.com/user-attachments/assets/0d7a49d6-e2e9-45cd-9235-c494c66db64f">

**Comment by MAbdurrehman1** [comment]
@buckyroberts Let me know once this is deployed.
We can test it on production
