### ISSUE TITLE
Invitation Code

### ISSUE THREAD

**Issue by roshanlam** [thenewboston-developers/thenewboston-Frontend#63]
Hey Bucky what's the invitation code? Wanna create create an account :)

**Comment by buckyroberts** [comment]
@roshanlam message me on Discord and I'll send you one. My username is thenewboston.

**Comment by JMC4987** [comment]
Dear Mr, Robert

Hi, I'm Ming. I wanna create an account. How do I get the invitation code? :)

Best regards 

J.M. Chiau

**Comment by nvm1411** [comment]
Hi Bucky, I wanna create an account, can i get a invitation code?
Thank you

**Comment by joshtechwise** [comment]
Good afternoon noon bucky. Hi I want to create an account and have access to your website. I need an invitation code

**Comment by bluecoinbear** [comment]
Hi Bucky, may I get invitation code? I want to create my account on your site. Thank you.
ps thanks millions, I had learn python from your youtube channel over 10 years ago. I had tutor many with python

**Comment by bluecoinbear** [comment]
sent you friend invitation in Discord, coin_63539

**Comment by M965491** [comment]
Hi Bucky, i want to create my account on your website. how can i get the invitation code.

**Comment by XavierFahrenheit** [comment]
Hi Bucky, i want to create my account on your website too. how can i get the invitation code.

**Comment by mrallam** [comment]
May I have an invitation code?

**Comment by Auwal1** [comment]
Good Mr bucky please can I have invitation code for me to create account to enable me access your website thank you

**Comment by Sir-Dennis** [comment]
> Hey Bucky what's the invitation code? Wanna create create an account :)

Good day Bucky, myself also would like to ask for invitation code in the new boston

**Comment by mrallam** [comment]
Hi Bucky
May i have an invitation code?
Thanks in advance

**Comment by JZersche** [comment]
I've friend requested you as well. 
Thank you in advance!

**Comment by Brucelees** [comment]
Hi Bucky, Please provide invitation code, sent request on discord
Thanks in advance!
